# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 368f6944b14468702625e39a4243e51008a7bbaff6fcb356e04e8bbcf9b6002550369d56ec25b1f3a6c9079af003f61b5544afed53a4ae7b5eb724e34c0cf31e

test:
  secret_key_base: 0bf1e40b2b575ec6a1fb8a308a6bcf82cefd29c35bb851de45a53ea61561c3d8b8a475dbd75469bcbcdf53580b730c936c5081a65dbbde3f8219b5f4ece86a93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
